---
- hosts: workers
  gather_facts: False
  tasks:
    - name: Setup APT operations to use caching proxy
      template: src=00proxy.j2 dest=/etc/apt/apt.conf.d/00proxy
    - name: Set hostname from DHCP
      copy: src=dhclient_hostname dest=/etc/dhcp/dhclient-exit-hooks.d/hostname
